# Generated by Django 3.1.7 on 2021-03-29 06:56

from django.db import migrations, models
import django.utils.timezone as tz


def set_my_defaults(apps, schema_editor):
    Goods = apps.get_model('main', 'Goods')
    for item in Goods.objects.all().iterator():
        item.created_on = tz.datetime(year=2000, month=1, day=1)
        item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210329_0351'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='created on'),
            preserve_default=False,
        ),
        migrations.RunPython(set_my_defaults),
        migrations.AlterField(
            model_name='goods',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created on'),
        ),
    ]
